#### In this notebook, I perform an initial cleaning of both thr socio-economic dataset and the crime dataset from the city of Chicago.
The goal of this step is to ensure consistent formatting, handle missing values, and prepare the data for further analysis.
This preprocessinh will enable two subsequent notebooks, one dedicatde to exploring the socio-economic indicators through statistical visualizations, and another focused on geospatial analysis of crime patterns across Chicago.These exploring analysis will ultimately support the development if an iteractive dashboard that highlights key insights about the city.

In [1]:
import pandas as pd

### Socio-economic indicator dataset

In [4]:
df=pd.read_csv('data/chicago_census.csv')
df.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           78 non-null     object
 2   PERCENT_OF_HOUSING_CROWDED                    78 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              78 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   78 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  78 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              78 non-null     float64
 7   PER_CAPITA_INCOME                             78 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 5.6+ KB

In [6]:
# We notice only two missing values
df.dropna(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           77 non-null     object
 2   PERCENT_OF_HOUSING_CROWDED                    77 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              77 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   77 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  77 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              77 non-null     float64
 7   PER_CAPITA_INCOME                             77 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 6.0+ KB

In [9]:
df.rename(columns={
    'PERCENT_OF_HOUSING_CROWDED':'pct_crowed_housing',
    'PERCENT_HOUSEHOLDS_BELOW_POVERTY':'pct_below_poverty',
    'PERCENT_AGED_16__UNEMPLOYED':'pct_unemployed',
    'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA':'pct_without_hs',
    'PERCENT_AGED_UNDER_18_OR_OVER_64':'pct_young_old',
    'PER_CAPITA_INCOME':'income_per_capita',
    'HARDSHIP_INDEX':'hardship_index',
    'COMMUNITY_AREA_NUMBER':'community_number',
    'COMMUNITY_AREA_NAME':'community_name'
},inplace=True)
df.columns.to_list()

['community_number',
 'community_name',
 'pct_crowed_housing',
 'pct_below_poverty',
 'pct_unemployed',
 'pct_without_hs',
 'pct_young_old',
 'income_per_capita',
 'hardship_index']

In [19]:
df.to_csv('data/chicago_census_clean.csv',index=False)

### Crime dataset

In [12]:
df1=pd.read_csv('data/chicago_crime.csv')
df1.head()

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,8/28/2004,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,6/26/2004,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,4/4/2011,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,12/30/2010,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2/2/2016,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     533 non-null    int64
 1   CASE_NUMBER            533 non-null    object
 2   DATE                   533 non-null    object
 3   BLOCK                  533 non-null    object
 4   IUCR                   533 non-null    object
 5   PRIMARY_TYPE           533 non-null    object
 6   DESCRIPTION            533 non-null    object
 7   LOCATION_DESCRIPTION   533 non-null    object
 8   ARREST                 533 non-null    bool
 9   DOMESTIC               533 non-null    bool
 10  BEAT                   533 non-null    int64
 11  DISTRICT               533 non-null    int64
 12  WARD                   490 non-null    float64
 13  COMMUNITY_AREA_NUMBER  490 non-null    float64
 14  FBICODE                533 non-null    object
 15  X_COORDINATE           529 non-null    float64
 16  Y_COORDINATE           529 non-null    float64
 17  YEAR                   533 non-null    int64
 18  LATITUDE               529 non-null    float64
 19  LONGITUDE              529 non-null    float64
 20  LOCATION               529 non-null    object
dtypes: bool(2), float64(6), int64(4), object(9)
memory usage: 80.3+ KB

In [14]:
# We notice many missing values
df1.dropna(inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 487 entries, 0 to 531
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     487 non-null    int64
 1   CASE_NUMBER            487 non-null    object
 2   DATE                   487 non-null    object
 3   BLOCK                  487 non-null    object
 4   IUCR                   487 non-null    object
 5   PRIMARY_TYPE           487 non-null    object
 6   DESCRIPTION            487 non-null    object
 7   LOCATION_DESCRIPTION   487 non-null    object
 8   ARREST                 487 non-null    bool
 9   DOMESTIC               487 non-null    bool
 10  BEAT                   487 non-null    int64
 11  DISTRICT               487 non-null    int64
 12  WARD                   487 non-null    float64
 13  COMMUNITY_AREA_NUMBER  487 non-null    float64
 14  FBICODE                487 non-null    object
 15  X_COORDINATE           487 non-null    float64
 16  Y_COORDINATE           487 non-null    float64
 17  YEAR                   487 non-null    int64
 18  LATITUDE               487 non-null    float64
 19  LONGITUDE              487 non-null    float64
 20  LOCATION               487 non-null    object
dtypes: bool(2), float64(6), int64(4), object(9)
memory usage: 77.0+ KB

In [16]:
# Convert DATE to datetime
df1['DATE']=pd.to_datetime(df1['DATE'])
df1['DATE'].dtype

dtype('<M8[ns]')

In [20]:
df1.to_csv('data/chicago_crime_clean.csv',index=False)